packages:
  - 'api/*'
  - 'api-tests'
  - 'docs'
  - 'collections'
  - 'data'
  - 'dash'
  - 'pkgs/*'
  - '!pkgs/payload-hooks-queue'
  - '!pkgs/payload-utils'
  - '!pkgs/durable-objects-nosql'
  - '!pkgs/payload-agent'
  - 'sdk/*'
  - 'sdks/*'
  - 'web/*'
  - 'workflows'
  - 'workers/*'
