import camelCase from 'camelcase'

const allProviders = [
  'OpenAI',
  'Anthropic',
  'Google',
  'Google AI Studio',
  'Amazon Bedrock',
  'Groq',
  'SambaNova',
  'Cohere',
  'Mistral',
  'Together',
  'Together 2',
  'Fireworks',
  'DeepInfra',
  'Lepton',
  'Novita',
  'Avian',
  'Lambda',
  'Azure',
  'Modal',
  'AnyScale',
  'Replicate',
  'Perplexity',
  'Recursal',
  'OctoAI',
  'DeepSeek',
  'Infermatic',
  'AI21',
  'Featherless',
  'Inflection',
  'xAI',
  'Cloudflare',
  'SF Compute',
  'Minimax',
  'Nineteen',
  'Liquid',
  'Stealth',
  'NCompass',
  'InferenceNet',
  'Friendli',
  'AionLabs',
  'Alibaba',
  'Nebius',
  'Chutes',
  'Kluster',
  'Crusoe',
  'Targon',
  'Ubicloud',
  'Parasail',
  'Phala',
  'Cent-ML',
  'Venice',
  'OpenInference',
  'Atoma',
  '01.AI',
  'HuggingFace',
  'Mancer',
  'Mancer 2',
  'Hyperbolic',
  'Hyperbolic 2',
  'Lynn 2',
  'Lynn',
  'Reflection',
  'NLP Cloud',
  'AI Core',
  'Aleph Alpha',
  'Stability AI',
  'Adept',
  'Mosaic ML',
  'Cerebras',
  'Cerebras 2',
  'Cerebras Cloud',
  'Nvidia AI',
  'Nvidia NIM',
  'Nvidia Inference',
  'Nvidia Cloud',
  'Nvidia Omniverse',
  'Nvidia Inference Cloud',
  'Nvidia AI Studio',
  'Nvidia AI Platform',
  'Nvidia AI Cloud',
  'Nvidia AI Inference',
  'Nvidia AI Omniverse',
  'Nvidia AI Platform Cloud',
  'Nvidia AI Platform Inference',
  'Nvidia AI Platform Omniverse',
  'Nvidia AI Platform Studio',
  'Nvidia AI Platform Cloud Studio',
  'Nvidia AI Platform Cloud Inference',
  'Nvidia AI Platform Cloud Omniverse',
  'Nvidia AI Platform Cloud Studio Inference',
  'Nvidia AI Platform Cloud Studio Omniverse',
  'Nvidia AI Platform Cloud Studio Inference Omniverse',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 2',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 3',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 4',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 5',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 6',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 7',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 8',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 9',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 10',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 11',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 12',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 13',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 14',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 15',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 16',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 17',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 18',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 19',
  'Nvidia AI Platform Cloud Studio Inference Omniverse 20',
  'Character AI',
  'Runway',
  'Runway ML',
  'Runway Gen',
  'Runway Gen 2',
  'Runway Gen 3',
  'Runway Gen 4',
  'Runway Gen 5',
  'Runway Gen 6',
  'Runway Gen 7',
  'Runway Gen 8',
  'Runway Gen 9',
  'Runway Gen 10',
  'Runway Gen 11',
  'Runway Gen 12',
  'Runway Gen 13',
  'Runway Gen 14',
  'Runway Gen 15',
  'Runway Gen 16',
  'Runway Gen 17',
  'Runway Gen 18',
  'Runway Gen 19',
  'Runway Gen 20',
  'Runway Gen 21',
  'Runway Gen 22',
  'Runway Gen 23',
  'Runway Gen 24',
  'Runway Gen 25',
  'Runway Gen 26',
  'Runway Gen 27',
  'Runway Gen 28',
  'Runway Gen 29',
  'Runway Gen 30',
  'Runway Gen 31',
  'Runway Gen 32',
  'Runway Gen 33',
  'Runway Gen 34',
  'Runway Gen 35',
  'Runway Gen 36',
  'Runway Gen 37',
  'Runway Gen 38',
  'Runway Gen 39',
  'Runway Gen 40',
  'Runway Gen 41',
  'Runway Gen 42',
  'Runway Gen 43',
  'Runway Gen 44',
  'Runway Gen 45',
  'Runway Gen 46',
  'Runway Gen 47',
  'Runway Gen 48',
  'Runway Gen 49',
  'Runway Gen 50',
  'Midjourney',
  'Midjourney AI',
  'Midjourney ML',
  'Midjourney Gen',
  'Midjourney Gen 2',
  'Midjourney Gen 3',
  'Midjourney Gen 4',
  'Midjourney Gen 5',
  'Midjourney Gen 6',
  'Midjourney Gen 7',
  'Midjourney Gen 8',
  'Midjourney Gen 9',
  'Midjourney Gen 10',
  'Midjourney Gen 11',
  'Midjourney Gen 12',
  'Midjourney Gen 13',
  'Midjourney Gen 14',
  'Midjourney Gen 15',
  'Midjourney Gen 16',
  'Midjourney Gen 17',
  'Midjourney Gen 18',
  'Midjourney Gen 19',
  'Midjourney Gen 20',
  'Midjourney Gen 21',
  'Midjourney Gen 22',
  'Midjourney Gen 23',
  'Midjourney Gen 24',
  'Midjourney Gen 25',
  'Midjourney Gen 26',
  'Midjourney Gen 27',
  'Midjourney Gen 28',
  'Midjourney Gen 29',
  'Midjourney Gen 30',
  'Midjourney Gen 31',
  'Midjourney Gen 32',
  'Midjourney Gen 33',
  'Midjourney Gen 34',
  'Midjourney Gen 35',
  'Midjourney Gen 36',
  'Midjourney Gen 37',
  'Midjourney Gen 38',
  'Midjourney Gen 39',
  'Midjourney Gen 40',
  'Midjourney Gen 41',
  'Midjourney Gen 42',
  'Midjourney Gen 43',
  'Midjourney Gen 44',
  'Midjourney Gen 45',
  'Midjourney Gen 46',
  'Midjourney Gen 47',
  'Midjourney Gen 48',
  'Midjourney Gen 49',
  'Midjourney Gen 50',
  'Stable Diffusion',
  'Stable Diffusion AI',
  'Stable Diffusion ML',
  'Stable Diffusion Gen',
  'Stable Diffusion Gen 2',
  'Stable Diffusion Gen 3',
  'Stable Diffusion Gen 4',
  'Stable Diffusion Gen 5',
  'Stable Diffusion Gen 6',
  'Stable Diffusion Gen 7',
  'Stable Diffusion Gen 8',
  'Stable Diffusion Gen 9',
  'Stable Diffusion Gen 10',
  'Stable Diffusion Gen 11',
  'Stable Diffusion Gen 12',
  'Stable Diffusion Gen 13',
  'Stable Diffusion Gen 14',
  'Stable Diffusion Gen 15',
  'Stable Diffusion Gen 16',
  'Stable Diffusion Gen 17',
  'Stable Diffusion Gen 18',
  'Stable Diffusion Gen 19',
  'Stable Diffusion Gen 20',
  'Stable Diffusion Gen 21',
  'Stable Diffusion Gen 22',
  'Stable Diffusion Gen 23',
  'Stable Diffusion Gen 24',
  'Stable Diffusion Gen 25',
  'Stable Diffusion Gen 26',
  'Stable Diffusion Gen 27',
  'Stable Diffusion Gen 28',
  'Stable Diffusion Gen 29',
  'Stable Diffusion Gen 30',
  'Stable Diffusion Gen 31',
  'Stable Diffusion Gen 32',
  'Stable Diffusion Gen 33',
  'Stable Diffusion Gen 34',
  'Stable Diffusion Gen 35',
  'Stable Diffusion Gen 36',
  'Stable Diffusion Gen 37',
  'Stable Diffusion Gen 38',
  'Stable Diffusion Gen 39',
  'Stable Diffusion Gen 40',
  'Stable Diffusion Gen 41',
  'Stable Diffusion Gen 42',
  'Stable Diffusion Gen 43',
  'Stable Diffusion Gen 44',
  'Stable Diffusion Gen 45',
  'Stable Diffusion Gen 46',
  'Stable Diffusion Gen 47',
  'Stable Diffusion Gen 48',
  'Stable Diffusion Gen 49',
  'Stable Diffusion Gen 50',
  'Hugging Face',
  'Hugging Face AI',
  'Hugging Face ML',
  'Hugging Face Gen',
  'Hugging Face Gen 2',
  'Hugging Face Gen 3',
  'Hugging Face Gen 4',
  'Hugging Face Gen 5',
  'Hugging Face Gen 6',
  'Hugging Face Gen 7',
  'Hugging Face Gen 8',
  'Hugging Face Gen 9',
  'Hugging Face Gen 10',
  'Hugging Face Gen 11',
  'Hugging Face Gen 12',
  'Hugging Face Gen 13',
  'Hugging Face Gen 14',
  'Hugging Face Gen 15',
  'Hugging Face Gen 16',
  'Hugging Face Gen 17',
  'Hugging Face Gen 18',
  'Hugging Face Gen 19',
  'Hugging Face Gen 20',
  'Hugging Face Gen 21',
  'Hugging Face Gen 22',
  'Hugging Face Gen 23',
  'Hugging Face Gen 24',
  'Hugging Face Gen 25',
  'Hugging Face Gen 26',
  'Hugging Face Gen 27',
  'Hugging Face Gen 28',
  'Hugging Face Gen 29',
  'Hugging Face Gen 30',
  'Hugging Face Gen 31',
  'Hugging Face Gen 32',
  'Hugging Face Gen 33',
  'Hugging Face Gen 34',
  'Hugging Face Gen 35',
  'Hugging Face Gen 36',
  'Hugging Face Gen 37',
  'Hugging Face Gen 38',
  'Hugging Face Gen 39',
  'Hugging Face Gen 40',
  'Hugging Face Gen 41',
  'Hugging Face Gen 42',
  'Hugging Face Gen 43',
  'Hugging Face Gen 44',
  'Hugging Face Gen 45',
  'Hugging Face Gen 46',
  'Hugging Face Gen 47',
  'Hugging Face Gen 48',
  'Hugging Face Gen 49',
  'Hugging Face Gen 50',
  'Databricks',
  'Databricks AI',
  'Databricks ML',
  'Databricks Gen',
  'Databricks Gen 2',
  'Databricks Gen 3',
  'Databricks Gen 4',
  'Databricks Gen 5',
  'Databricks Gen 6',
  'Databricks Gen 7',
  'Databricks Gen 8',
  'Databricks Gen 9',
  'Databricks Gen 10',
  'Databricks Gen 11',
  'Databricks Gen 12',
  'Databricks Gen 13',
  'Databricks Gen 14',
  'Databricks Gen 15',
  'Databricks Gen 16',
  'Databricks Gen 17',
  'Databricks Gen 18',
  'Databricks Gen 19',
  'Databricks Gen 20',
  'Databricks Gen 21',
  'Databricks Gen 22',
  'Databricks Gen 23',
  'Databricks Gen 24',
  'Databricks Gen 25',
  'Databricks Gen 26',
  'Databricks Gen 27',
  'Databricks Gen 28',
  'Databricks Gen 29',
  'Databricks Gen 30',
  'Databricks Gen 31',
  'Databricks Gen 32',
  'Databricks Gen 33',
  'Databricks Gen 34',
  'Databricks Gen 35',
  'Databricks Gen 36',
  'Databricks Gen 37',
  'Databricks Gen 38',
  'Databricks Gen 39',
  'Databricks Gen 40',
  'Databricks Gen 41',
  'Databricks Gen 42',
  'Databricks Gen 43',
  'Databricks Gen 44',
  'Databricks Gen 45',
  'Databricks Gen 46',
  'Databricks Gen 47',
  'Databricks Gen 48',
  'Databricks Gen 49',
  'Databricks Gen 50',
  'Weights & Biases',
  'Weights & Biases AI',
  'Weights & Biases ML',
  'Weights & Biases Gen',
  'Weights & Biases Gen 2',
  'Weights & Biases Gen 3',
  'Weights & Biases Gen 4',
  'Weights & Biases Gen 5',
  'Weights & Biases Gen 6',
  'Weights & Biases Gen 7',
  'Weights & Biases Gen 8',
  'Weights & Biases Gen 9',
  'Weights & Biases Gen 10',
  'Cohere AI',
  'Cohere Command',
  'Cohere Command R',
  'Cohere Command XL',
  'Cohere Embed',
  'Cohere Generate',
  'Cohere Represent',
  'Cohere Summarize',
  'Anthropic API',
  'OpenAI API',
  'OpenAI Platform',
  'OpenAI Completions',
  'OpenAI Chat',
]

export const getProviderName = (provider: string) => {
  // Reverse a camelCase string into the provider's name

  switch (provider) {
    case 'vertex':
      return 'Google'
    case 'google':
      return 'Google AI Studio'
    case 'openai':
      return 'OpenAI'
    case 'anthropic':
      return 'Anthropic'
    default:
      return allProviders.find((p) => camelCase(p) === provider)
  }
}
