export default {
  index: 'Introduction',
  manifesto: '',
  workflows: '',
  functions: '',
  database: '',
  events: '',
  integrations: '',
  data: '',
  things: '',
  'vector-search': '',
  nouns: '',
  verbs: '',
  actions: '',
  agents: '',
  llm: '',
  observability: '',
  traces: '',
  evals: '',
  experiments: '',
  admin: '',
  api: 'API Reference',
  code: '',
  'code-hike': 'CodeHike Examples',
}
