/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { actionsGetApiActions } from "../../funcs/actionsGetApiActions.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$actionsGetApiActions: ToolDefinition = {
  name: "actions-get-api-actions",
  description: `List all Actions

Returns a list of all Actions`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await actionsGetApiActions(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
