/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsDeleteApiAgentsId } from "../../funcs/agentsDeleteApiAgentsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiAgentsIdRequest$inboundSchema,
};

export const tool$agentsDeleteApiAgentsId: ToolDefinition<typeof args> = {
  name: "agents-delete-api-agents-id",
  description: `Delete a Agent

Deletes a specific Agent by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentsDeleteApiAgentsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
