/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsGetApiAgentsId } from "../../funcs/agentsGetApiAgentsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiAgentsIdRequest$inboundSchema,
};

export const tool$agentsGetApiAgentsId: ToolDefinition<typeof args> = {
  name: "agents-get-api-agents-id",
  description: `Get a specific Agent

Returns a specific Agent by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentsGetApiAgentsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
