/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { categoriesGetApiIntegrationCategories } from "../../funcs/categoriesGetApiIntegrationCategories.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$categoriesGetApiIntegrationCategories: ToolDefinition = {
  name: "categories-get-api-integration-categories",
  description: `List all Categories

Returns a list of all Categories`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await categoriesGetApiIntegrationCategories(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
