/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectionsDeleteApiConnectionsId } from "../../funcs/connectionsDeleteApiConnectionsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiConnectionsIdRequest$inboundSchema,
};

export const tool$connectionsDeleteApiConnectionsId: ToolDefinition<
  typeof args
> = {
  name: "connections-delete-api-connections-id",
  description: `Delete a Connection

Deletes a specific Connection by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await connectionsDeleteApiConnectionsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
