/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { datasetsGetApiDatasetsId } from "../../funcs/datasetsGetApiDatasetsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiDatasetsIdRequest$inboundSchema,
};

export const tool$datasetsGetApiDatasetsId: ToolDefinition<typeof args> = {
  name: "datasets-get-api-datasets-id",
  description: `Get a specific Dataset

Returns a specific Dataset by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await datasetsGetApiDatasetsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
