/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deploymentsGetApiDeploymentsId } from "../../funcs/deploymentsGetApiDeploymentsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiDeploymentsIdRequest$inboundSchema,
};

export const tool$deploymentsGetApiDeploymentsId: ToolDefinition<typeof args> =
  {
    name: "deployments-get-api-deployments-id",
    description: `Get a specific Deployment

Returns a specific Deployment by ID`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await deploymentsGetApiDeploymentsId(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
