/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { domainsGetApiDomains } from "../../funcs/domainsGetApiDomains.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$domainsGetApiDomains: ToolDefinition = {
  name: "domains-get-api-domains",
  description: `List all Domains

Returns a list of all Domains`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await domainsGetApiDomains(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
