/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { domainsGetApiDomainsId } from "../../funcs/domainsGetApiDomainsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiDomainsIdRequest$inboundSchema,
};

export const tool$domainsGetApiDomainsId: ToolDefinition<typeof args> = {
  name: "domains-get-api-domains-id",
  description: `Get a specific Domain

Returns a specific Domain by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await domainsGetApiDomainsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
