/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evalsGetApiEvalsId } from "../../funcs/evalsGetApiEvalsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiEvalsIdRequest$inboundSchema,
};

export const tool$evalsGetApiEvalsId: ToolDefinition<typeof args> = {
  name: "evals-get-api-evals-id",
  description: `Get a specific Eval

Returns a specific Eval by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await evalsGetApiEvalsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
