/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evalsDeleteApiEvalsId } from "../../funcs/evalsDeleteApiEvalsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiEvalsIdRequest$inboundSchema,
};

export const tool$evalsDeleteApiEvalsId: ToolDefinition<typeof args> = {
  name: "evals-delete-api-evals-id",
  description: `Delete a Eval

Deletes a specific Eval by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await evalsDeleteApiEvalsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
