/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evalsGetApiEvals } from "../../funcs/evalsGetApiEvals.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$evalsGetApiEvals: ToolDefinition = {
  name: "evals-get-api-evals",
  description: `List all Evals

Returns a list of all Evals`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await evalsGetApiEvals(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
