/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsGetApiEventsId } from "../../funcs/eventsGetApiEventsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiEventsIdRequest$inboundSchema,
};

export const tool$eventsGetApiEventsId: ToolDefinition<typeof args> = {
  name: "events-get-api-events-id",
  description: `Get a specific Event

Returns a specific Event by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsGetApiEventsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
