/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { experimentMetricsGetApiExperimentMetrics } from "../../funcs/experimentMetricsGetApiExperimentMetrics.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$experimentMetricsGetApiExperimentMetrics: ToolDefinition = {
  name: "experiment-metrics-get-api-experiment-metrics",
  description: `List all Experiment Metrics

Returns a list of all Experiment Metrics`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await experimentMetricsGetApiExperimentMetrics(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
