/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { experimentsGetApiExperimentsId } from "../../funcs/experimentsGetApiExperimentsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiExperimentsIdRequest$inboundSchema,
};

export const tool$experimentsGetApiExperimentsId: ToolDefinition<typeof args> =
  {
    name: "experiments-get-api-experiments-id",
    description: `Get a specific Experiment

Returns a specific Experiment by ID`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await experimentsGetApiExperimentsId(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
