/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { generationBatchesGetApiGenerationBatchesId } from "../../funcs/generationBatchesGetApiGenerationBatchesId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiGenerationBatchesIdRequest$inboundSchema,
};

export const tool$generationBatchesGetApiGenerationBatchesId: ToolDefinition<
  typeof args
> = {
  name: "generation-batches-get-api-generation-batches-id",
  description: `Get a specific Generation Batch

Returns a specific Generation Batch by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await generationBatchesGetApiGenerationBatchesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
