/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { generationsGetApiGenerationsId } from "../../funcs/generationsGetApiGenerationsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiGenerationsIdRequest$inboundSchema,
};

export const tool$generationsGetApiGenerationsId: ToolDefinition<typeof args> =
  {
    name: "generations-get-api-generations-id",
    description: `Get a specific Generation

Returns a specific Generation by ID`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await generationsGetApiGenerationsId(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
