/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { goalsGetApiGoalsId } from "../../funcs/goalsGetApiGoalsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiGoalsIdRequest$inboundSchema,
};

export const tool$goalsGetApiGoalsId: ToolDefinition<typeof args> = {
  name: "goals-get-api-goals-id",
  description: `Get a specific Goal

Returns a specific Goal by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await goalsGetApiGoalsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
