/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsDeleteApiIntegrationsId } from "../../funcs/integrationsDeleteApiIntegrationsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiIntegrationsIdRequest$inboundSchema,
};

export const tool$integrationsDeleteApiIntegrationsId: ToolDefinition<
  typeof args
> = {
  name: "integrations-delete-api-integrations-id",
  description: `Delete a Integration

Deletes a specific Integration by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationsDeleteApiIntegrationsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
