/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsGetApiIntegrations } from "../../funcs/integrationsGetApiIntegrations.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$integrationsGetApiIntegrations: ToolDefinition = {
  name: "integrations-get-api-integrations",
  description: `List all Integrations

Returns a list of all Integrations`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await integrationsGetApiIntegrations(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
