/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { kpIsDeleteApiKpisId } from "../../funcs/kpIsDeleteApiKpisId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiKpisIdRequest$inboundSchema,
};

export const tool$kpIsDeleteApiKpisId: ToolDefinition<typeof args> = {
  name: "KP-is-delete-api-kpis-id",
  description: `Delete a KPI

Deletes a specific KPI by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await kpIsDeleteApiKpisId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
