/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { kpIsGetApiKpis } from "../../funcs/kpIsGetApiKpis.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$kpIsGetApiKpis: ToolDefinition = {
  name: "KP-is-get-api-kpis",
  description: `List all KPIs

Returns a list of all KPIs`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await kpIsGetApiKpis(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
