/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { labsGetApiLabsId } from "../../funcs/labsGetApiLabsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiLabsIdRequest$inboundSchema,
};

export const tool$labsGetApiLabsId: ToolDefinition<typeof args> = {
  name: "labs-get-api-labs-id",
  description: `Get a specific Lab

Returns a specific Lab by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await labsGetApiLabsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
