/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modelsGetApiModels } from "../../funcs/modelsGetApiModels.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$modelsGetApiModels: ToolDefinition = {
  name: "models-get-api-models",
  description: `List all Models

Returns a list of all Models`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await modelsGetApiModels(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
