/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modelsGetApiModelsId } from "../../funcs/modelsGetApiModelsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiModelsIdRequest$inboundSchema,
};

export const tool$modelsGetApiModelsId: ToolDefinition<typeof args> = {
  name: "models-get-api-models-id",
  description: `Get a specific Model

Returns a specific Model by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await modelsGetApiModelsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
