/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modulesGetApiModules } from "../../funcs/modulesGetApiModules.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$modulesGetApiModules: ToolDefinition = {
  name: "modules-get-api-modules",
  description: `List all Modules

Returns a list of all Modules`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await modulesGetApiModules(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
