/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modulesGetApiModulesId } from "../../funcs/modulesGetApiModulesId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiModulesIdRequest$inboundSchema,
};

export const tool$modulesGetApiModulesId: ToolDefinition<typeof args> = {
  name: "modules-get-api-modules-id",
  description: `Get a specific Module

Returns a specific Module by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await modulesGetApiModulesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
