/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { nounsGetApiNounsId } from "../../funcs/nounsGetApiNounsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiNounsIdRequest$inboundSchema,
};

export const tool$nounsGetApiNounsId: ToolDefinition<typeof args> = {
  name: "nouns-get-api-nouns-id",
  description: `Get a specific Noun

Returns a specific Noun by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await nounsGetApiNounsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
