/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oauthClientsGetApiOauthClients } from "../../funcs/oauthClientsGetApiOauthClients.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$oauthClientsGetApiOauthClients: ToolDefinition = {
  name: "oauth-clients-get-api-oauth-clients",
  description: `List all Oauth Clients

Returns a list of all Oauth Clients`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await oauthClientsGetApiOauthClients(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
