/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oauthClientsDeleteApiOauthClientsId } from "../../funcs/oauthClientsDeleteApiOauthClientsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiOauthClientsIdRequest$inboundSchema,
};

export const tool$oauthClientsDeleteApiOauthClientsId: ToolDefinition<
  typeof args
> = {
  name: "oauth-clients-delete-api-oauth-clients-id",
  description: `Delete a Oauth Client

Deletes a specific Oauth Client by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await oauthClientsDeleteApiOauthClientsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
