/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oauthClientsGetApiOauthClientsId } from "../../funcs/oauthClientsGetApiOauthClientsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiOauthClientsIdRequest$inboundSchema,
};

export const tool$oauthClientsGetApiOauthClientsId: ToolDefinition<
  typeof args
> = {
  name: "oauth-clients-get-api-oauth-clients-id",
  description: `Get a specific Oauth Client

Returns a specific Oauth Client by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await oauthClientsGetApiOauthClientsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
