/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsGetApiProjectsId } from "../../funcs/projectsGetApiProjectsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiProjectsIdRequest$inboundSchema,
};

export const tool$projectsGetApiProjectsId: ToolDefinition<typeof args> = {
  name: "projects-get-api-projects-id",
  description: `Get a specific Project

Returns a specific Project by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await projectsGetApiProjectsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
