/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsGetApiProjects } from "../../funcs/projectsGetApiProjects.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$projectsGetApiProjects: ToolDefinition = {
  name: "projects-get-api-projects",
  description: `List all Projects

Returns a list of all Projects`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await projectsGetApiProjects(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
