/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { promptsGetApiPromptsId } from "../../funcs/promptsGetApiPromptsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiPromptsIdRequest$inboundSchema,
};

export const tool$promptsGetApiPromptsId: ToolDefinition<typeof args> = {
  name: "prompts-get-api-prompts-id",
  description: `Get a specific Prompt

Returns a specific Prompt by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await promptsGetApiPromptsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
