/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { providersDeleteApiProvidersId } from "../../funcs/providersDeleteApiProvidersId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiProvidersIdRequest$inboundSchema,
};

export const tool$providersDeleteApiProvidersId: ToolDefinition<typeof args> = {
  name: "providers-delete-api-providers-id",
  description: `Delete a Provider

Deletes a specific Provider by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await providersDeleteApiProvidersId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
