/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { providersGetApiProviders } from "../../funcs/providersGetApiProviders.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$providersGetApiProviders: ToolDefinition = {
  name: "providers-get-api-providers",
  description: `List all Providers

Returns a list of all Providers`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await providersGetApiProviders(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
