/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { providersGetApiProvidersId } from "../../funcs/providersGetApiProvidersId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiProvidersIdRequest$inboundSchema,
};

export const tool$providersGetApiProvidersId: ToolDefinition<typeof args> = {
  name: "providers-get-api-providers-id",
  description: `Get a specific Provider

Returns a specific Provider by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await providersGetApiProvidersId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
