/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { queuesGetApiQueuesId } from "../../funcs/queuesGetApiQueuesId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiQueuesIdRequest$inboundSchema,
};

export const tool$queuesGetApiQueuesId: ToolDefinition<typeof args> = {
  name: "queues-get-api-queues-id",
  description: `Get a specific Queue

Returns a specific Queue by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await queuesGetApiQueuesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
