/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rolesDeleteApiRolesId } from "../../funcs/rolesDeleteApiRolesId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiRolesIdRequest$inboundSchema,
};

export const tool$rolesDeleteApiRolesId: ToolDefinition<typeof args> = {
  name: "roles-delete-api-roles-id",
  description: `Delete a Role

Deletes a specific Role by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await rolesDeleteApiRolesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
