/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { settingsGetApiSettingsId } from "../../funcs/settingsGetApiSettingsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiSettingsIdRequest$inboundSchema,
};

export const tool$settingsGetApiSettingsId: ToolDefinition<typeof args> = {
  name: "settings-get-api-settings-id",
  description: `Get a specific Setting

Returns a specific Setting by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await settingsGetApiSettingsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
