/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { settingsDeleteApiSettingsId } from "../../funcs/settingsDeleteApiSettingsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiSettingsIdRequest$inboundSchema,
};

export const tool$settingsDeleteApiSettingsId: ToolDefinition<typeof args> = {
  name: "settings-delete-api-settings-id",
  description: `Delete a Setting

Deletes a specific Setting by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await settingsDeleteApiSettingsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
