/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagsGetApiTagsId } from "../../funcs/tagsGetApiTagsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiTagsIdRequest$inboundSchema,
};

export const tool$tagsGetApiTagsId: ToolDefinition<typeof args> = {
  name: "tags-get-api-tags-id",
  description: `Get a specific Tag

Returns a specific Tag by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tagsGetApiTagsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
