/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagsGetApiTags } from "../../funcs/tagsGetApiTags.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$tagsGetApiTags: ToolDefinition = {
  name: "tags-get-api-tags",
  description: `List all Tags

Returns a list of all Tags`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await tagsGetApiTags(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
