/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tracesGetApiTracesId } from "../../funcs/tracesGetApiTracesId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiTracesIdRequest$inboundSchema,
};

export const tool$tracesGetApiTracesId: ToolDefinition<typeof args> = {
  name: "traces-get-api-traces-id",
  description: `Get a specific Trace

Returns a specific Trace by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tracesGetApiTracesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
