/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { triggersGetApiIntegrationTriggersId } from "../../funcs/triggersGetApiIntegrationTriggersId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiIntegrationTriggersIdRequest$inboundSchema,
};

export const tool$triggersGetApiIntegrationTriggersId: ToolDefinition<
  typeof args
> = {
  name: "triggers-get-api-integration-triggers-id",
  description: `Get a specific Trigger

Returns a specific Trigger by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await triggersGetApiIntegrationTriggersId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
