/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { typesGetApiTypes } from "../../funcs/typesGetApiTypes.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$typesGetApiTypes: ToolDefinition = {
  name: "types-get-api-types",
  description: `List all Types

Returns a list of all Types`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await typesGetApiTypes(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
