/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksGetApiWebhooksId } from "../../funcs/webhooksGetApiWebhooksId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetApiWebhooksIdRequest$inboundSchema,
};

export const tool$webhooksGetApiWebhooksId: ToolDefinition<typeof args> = {
  name: "webhooks-get-api-webhooks-id",
  description: `Get a specific Webhook

Returns a specific Webhook by ID`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksGetApiWebhooksId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
