/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workflowsGetApiWorkflows } from "../../funcs/workflowsGetApiWorkflows.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$workflowsGetApiWorkflows: ToolDefinition = {
  name: "workflows-get-api-workflows",
  description: `List all Workflows

Returns a list of all Workflows`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await workflowsGetApiWorkflows(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
