/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { categoriesDeleteApiIntegrationCategoriesId } from "../funcs/categoriesDeleteApiIntegrationCategoriesId.js";
import { categoriesGetApiIntegrationCategories } from "../funcs/categoriesGetApiIntegrationCategories.js";
import { categoriesGetApiIntegrationCategoriesId } from "../funcs/categoriesGetApiIntegrationCategoriesId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Categories extends ClientSDK {
  /**
   * List all Categories
   *
   * @remarks
   * Returns a list of all Categories
   */
  async getApiIntegrationCategories(
    options?: RequestOptions,
  ): Promise<operations.GetApiIntegrationCategoriesResponseBody> {
    return unwrapAsync(categoriesGetApiIntegrationCategories(
      this,
      options,
    ));
  }

  /**
   * Get a specific Category
   *
   * @remarks
   * Returns a specific Category by ID
   */
  async getApiIntegrationCategoriesId(
    request: operations.GetApiIntegrationCategoriesIdRequest,
    options?: RequestOptions,
  ): Promise<components.Category> {
    return unwrapAsync(categoriesGetApiIntegrationCategoriesId(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a Category
   *
   * @remarks
   * Deletes a specific Category by ID
   */
  async deleteApiIntegrationCategoriesId(
    request: operations.DeleteApiIntegrationCategoriesIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteApiIntegrationCategoriesIdResponseBody> {
    return unwrapAsync(categoriesDeleteApiIntegrationCategoriesId(
      this,
      request,
      options,
    ));
  }
}
