/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { labsDeleteApiLabsId } from "../funcs/labsDeleteApiLabsId.js";
import { labsGetApiLabs } from "../funcs/labsGetApiLabs.js";
import { labsGetApiLabsId } from "../funcs/labsGetApiLabsId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Labs extends ClientSDK {
  /**
   * List all Labs
   *
   * @remarks
   * Returns a list of all Labs
   */
  async getApiLabs(
    options?: RequestOptions,
  ): Promise<operations.GetApiLabsResponseBody> {
    return unwrapAsync(labsGetApiLabs(
      this,
      options,
    ));
  }

  /**
   * Get a specific Lab
   *
   * @remarks
   * Returns a specific Lab by ID
   */
  async getApiLabsId(
    request: operations.GetApiLabsIdRequest,
    options?: RequestOptions,
  ): Promise<components.Lab> {
    return unwrapAsync(labsGetApiLabsId(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a Lab
   *
   * @remarks
   * Deletes a specific Lab by ID
   */
  async deleteApiLabsId(
    request: operations.DeleteApiLabsIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteApiLabsIdResponseBody> {
    return unwrapAsync(labsDeleteApiLabsId(
      this,
      request,
      options,
    ));
  }
}
