/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oauthClientsDeleteApiOauthClientsId } from "../funcs/oauthClientsDeleteApiOauthClientsId.js";
import { oauthClientsGetApiOauthClients } from "../funcs/oauthClientsGetApiOauthClients.js";
import { oauthClientsGetApiOauthClientsId } from "../funcs/oauthClientsGetApiOauthClientsId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class OauthClients extends ClientSDK {
  /**
   * List all Oauth Clients
   *
   * @remarks
   * Returns a list of all Oauth Clients
   */
  async getApiOauthClients(
    options?: RequestOptions,
  ): Promise<operations.GetApiOauthClientsResponseBody> {
    return unwrapAsync(oauthClientsGetApiOauthClients(
      this,
      options,
    ));
  }

  /**
   * Get a specific Oauth Client
   *
   * @remarks
   * Returns a specific Oauth Client by ID
   */
  async getApiOauthClientsId(
    request: operations.GetApiOauthClientsIdRequest,
    options?: RequestOptions,
  ): Promise<components.OauthClient> {
    return unwrapAsync(oauthClientsGetApiOauthClientsId(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a Oauth Client
   *
   * @remarks
   * Deletes a specific Oauth Client by ID
   */
  async deleteApiOauthClientsId(
    request: operations.DeleteApiOauthClientsIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteApiOauthClientsIdResponseBody> {
    return unwrapAsync(oauthClientsDeleteApiOauthClientsId(
      this,
      request,
      options,
    ));
  }
}
