import { z } from 'zod'

export const APIDefinitionSchema = z.object({
  icon: z.string().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  url: z.string().optional(),
  endpoints: z.record(z.string()).optional(),
  resources: z.record(z.string()).optional(),
  login: z.string().optional(),
  account: z.string().optional(),
  signup: z.string().optional(),
  subscribe: z.string().optional(),
  prices: z.record(z.string()).optional(),
  docs: z.string().optional(),
  site: z.string().optional(),
  repo: z.string().optional(),
  type: z.enum(['data', 'services', 'commerce', 'ai']).optional(),
  from: z.string().optional(),
  version: z.string().optional(),
  updated: z.string().optional(),
  build: z.string().optional(),
  author: z.string().optional(),
  license: z.string().optional(),
})

export const APIUserSchema = z.object({
  name: z.string().optional(),
  email: z.string().optional(),
  org: z.string().optional(),
  image: z.string().optional(),
  authenticated: z.boolean(),
  admin: z.boolean().optional(),
  plan: z.enum(['Free', 'Build', 'Grow', 'Scale', 'Enterprise']),
  upgrade: z.string().optional(),
  support: z.string().optional(),
  browser: z.string().optional(),
  os: z.string(),
  ip: z.string(),
  isp: z.string(),
  flag: z.string(),
  zipcode: z.string().optional(),
  city: z.string(),
  metro: z.string(),
  region: z.string(),
  country: z.string(),
  continent: z.string(),
  requestId: z.string(),
  localTime: z.string(),
  timezone: z.string(),
  edgeLocation: z.string(),
  edgeDistanceMiles: z.number().optional(),
  edgeDistanceKilometers: z.number().optional(),
  latencyMilliseconds: z.number(),
  recentInteractions: z.number(),
  trustScore: z.number(),
  userAgent: z.string().optional(),
  serviceLatency: z.number().optional(),
})

export const FlexibleAPILinksSchema = z.object({
  home: z.string().describe('Home page'),
  self: z.string().describe('Current page'),
  next: z.string().optional().describe('Next page'),
  prev: z.string().optional().describe('Previous page'),
  last: z.string().optional().describe('Last page'),
})
