/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteApiOauthTokensIdRequest = {
  /**
   * The ID of the Oauth Token
   */
  id: string;
};

/**
 * Successfully deleted
 */
export type DeleteApiOauthTokensIdResponseBody = {
  message?: string | undefined;
};

/** @internal */
export const DeleteApiOauthTokensIdRequest$inboundSchema: z.ZodType<
  DeleteApiOauthTokensIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteApiOauthTokensIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteApiOauthTokensIdRequest$outboundSchema: z.ZodType<
  DeleteApiOauthTokensIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiOauthTokensIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiOauthTokensIdRequest$ {
  /** @deprecated use `DeleteApiOauthTokensIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteApiOauthTokensIdRequest$inboundSchema;
  /** @deprecated use `DeleteApiOauthTokensIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteApiOauthTokensIdRequest$outboundSchema;
  /** @deprecated use `DeleteApiOauthTokensIdRequest$Outbound` instead. */
  export type Outbound = DeleteApiOauthTokensIdRequest$Outbound;
}

export function deleteApiOauthTokensIdRequestToJSON(
  deleteApiOauthTokensIdRequest: DeleteApiOauthTokensIdRequest,
): string {
  return JSON.stringify(
    DeleteApiOauthTokensIdRequest$outboundSchema.parse(
      deleteApiOauthTokensIdRequest,
    ),
  );
}

export function deleteApiOauthTokensIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiOauthTokensIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApiOauthTokensIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiOauthTokensIdRequest' from JSON`,
  );
}

/** @internal */
export const DeleteApiOauthTokensIdResponseBody$inboundSchema: z.ZodType<
  DeleteApiOauthTokensIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
});

/** @internal */
export type DeleteApiOauthTokensIdResponseBody$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const DeleteApiOauthTokensIdResponseBody$outboundSchema: z.ZodType<
  DeleteApiOauthTokensIdResponseBody$Outbound,
  z.ZodTypeDef,
  DeleteApiOauthTokensIdResponseBody
> = z.object({
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiOauthTokensIdResponseBody$ {
  /** @deprecated use `DeleteApiOauthTokensIdResponseBody$inboundSchema` instead. */
  export const inboundSchema = DeleteApiOauthTokensIdResponseBody$inboundSchema;
  /** @deprecated use `DeleteApiOauthTokensIdResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    DeleteApiOauthTokensIdResponseBody$outboundSchema;
  /** @deprecated use `DeleteApiOauthTokensIdResponseBody$Outbound` instead. */
  export type Outbound = DeleteApiOauthTokensIdResponseBody$Outbound;
}

export function deleteApiOauthTokensIdResponseBodyToJSON(
  deleteApiOauthTokensIdResponseBody: DeleteApiOauthTokensIdResponseBody,
): string {
  return JSON.stringify(
    DeleteApiOauthTokensIdResponseBody$outboundSchema.parse(
      deleteApiOauthTokensIdResponseBody,
    ),
  );
}

export function deleteApiOauthTokensIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiOauthTokensIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteApiOauthTokensIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiOauthTokensIdResponseBody' from JSON`,
  );
}
