/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteApiPromptsIdRequest = {
  /**
   * The ID of the Prompt
   */
  id: string;
};

/**
 * Successfully deleted
 */
export type DeleteApiPromptsIdResponseBody = {
  message?: string | undefined;
};

/** @internal */
export const DeleteApiPromptsIdRequest$inboundSchema: z.ZodType<
  DeleteApiPromptsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteApiPromptsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteApiPromptsIdRequest$outboundSchema: z.ZodType<
  DeleteApiPromptsIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiPromptsIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiPromptsIdRequest$ {
  /** @deprecated use `DeleteApiPromptsIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteApiPromptsIdRequest$inboundSchema;
  /** @deprecated use `DeleteApiPromptsIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteApiPromptsIdRequest$outboundSchema;
  /** @deprecated use `DeleteApiPromptsIdRequest$Outbound` instead. */
  export type Outbound = DeleteApiPromptsIdRequest$Outbound;
}

export function deleteApiPromptsIdRequestToJSON(
  deleteApiPromptsIdRequest: DeleteApiPromptsIdRequest,
): string {
  return JSON.stringify(
    DeleteApiPromptsIdRequest$outboundSchema.parse(deleteApiPromptsIdRequest),
  );
}

export function deleteApiPromptsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiPromptsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApiPromptsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiPromptsIdRequest' from JSON`,
  );
}

/** @internal */
export const DeleteApiPromptsIdResponseBody$inboundSchema: z.ZodType<
  DeleteApiPromptsIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
});

/** @internal */
export type DeleteApiPromptsIdResponseBody$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const DeleteApiPromptsIdResponseBody$outboundSchema: z.ZodType<
  DeleteApiPromptsIdResponseBody$Outbound,
  z.ZodTypeDef,
  DeleteApiPromptsIdResponseBody
> = z.object({
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiPromptsIdResponseBody$ {
  /** @deprecated use `DeleteApiPromptsIdResponseBody$inboundSchema` instead. */
  export const inboundSchema = DeleteApiPromptsIdResponseBody$inboundSchema;
  /** @deprecated use `DeleteApiPromptsIdResponseBody$outboundSchema` instead. */
  export const outboundSchema = DeleteApiPromptsIdResponseBody$outboundSchema;
  /** @deprecated use `DeleteApiPromptsIdResponseBody$Outbound` instead. */
  export type Outbound = DeleteApiPromptsIdResponseBody$Outbound;
}

export function deleteApiPromptsIdResponseBodyToJSON(
  deleteApiPromptsIdResponseBody: DeleteApiPromptsIdResponseBody,
): string {
  return JSON.stringify(
    DeleteApiPromptsIdResponseBody$outboundSchema.parse(
      deleteApiPromptsIdResponseBody,
    ),
  );
}

export function deleteApiPromptsIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiPromptsIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApiPromptsIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiPromptsIdResponseBody' from JSON`,
  );
}
