/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteApiGenerationsIdRequest = {
  /**
   * The ID of the Generation
   */
  id: string;
};

/**
 * Successfully deleted
 */
export type DeleteApiGenerationsIdResponseBody = {
  message?: string | undefined;
};

/** @internal */
export const DeleteApiGenerationsIdRequest$inboundSchema: z.ZodType<
  DeleteApiGenerationsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteApiGenerationsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteApiGenerationsIdRequest$outboundSchema: z.ZodType<
  DeleteApiGenerationsIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiGenerationsIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiGenerationsIdRequest$ {
  /** @deprecated use `DeleteApiGenerationsIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteApiGenerationsIdRequest$inboundSchema;
  /** @deprecated use `DeleteApiGenerationsIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteApiGenerationsIdRequest$outboundSchema;
  /** @deprecated use `DeleteApiGenerationsIdRequest$Outbound` instead. */
  export type Outbound = DeleteApiGenerationsIdRequest$Outbound;
}

export function deleteApiGenerationsIdRequestToJSON(
  deleteApiGenerationsIdRequest: DeleteApiGenerationsIdRequest,
): string {
  return JSON.stringify(
    DeleteApiGenerationsIdRequest$outboundSchema.parse(
      deleteApiGenerationsIdRequest,
    ),
  );
}

export function deleteApiGenerationsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiGenerationsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApiGenerationsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiGenerationsIdRequest' from JSON`,
  );
}

/** @internal */
export const DeleteApiGenerationsIdResponseBody$inboundSchema: z.ZodType<
  DeleteApiGenerationsIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
});

/** @internal */
export type DeleteApiGenerationsIdResponseBody$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const DeleteApiGenerationsIdResponseBody$outboundSchema: z.ZodType<
  DeleteApiGenerationsIdResponseBody$Outbound,
  z.ZodTypeDef,
  DeleteApiGenerationsIdResponseBody
> = z.object({
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiGenerationsIdResponseBody$ {
  /** @deprecated use `DeleteApiGenerationsIdResponseBody$inboundSchema` instead. */
  export const inboundSchema = DeleteApiGenerationsIdResponseBody$inboundSchema;
  /** @deprecated use `DeleteApiGenerationsIdResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    DeleteApiGenerationsIdResponseBody$outboundSchema;
  /** @deprecated use `DeleteApiGenerationsIdResponseBody$Outbound` instead. */
  export type Outbound = DeleteApiGenerationsIdResponseBody$Outbound;
}

export function deleteApiGenerationsIdResponseBodyToJSON(
  deleteApiGenerationsIdResponseBody: DeleteApiGenerationsIdResponseBody,
): string {
  return JSON.stringify(
    DeleteApiGenerationsIdResponseBody$outboundSchema.parse(
      deleteApiGenerationsIdResponseBody,
    ),
  );
}

export function deleteApiGenerationsIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiGenerationsIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteApiGenerationsIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiGenerationsIdResponseBody' from JSON`,
  );
}
