/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteApiTriggersIdRequest = {
  /**
   * The ID of the Trigger
   */
  id: string;
};

/**
 * Successfully deleted
 */
export type DeleteApiTriggersIdResponseBody = {
  message?: string | undefined;
};

/** @internal */
export const DeleteApiTriggersIdRequest$inboundSchema: z.ZodType<
  DeleteApiTriggersIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteApiTriggersIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteApiTriggersIdRequest$outboundSchema: z.ZodType<
  DeleteApiTriggersIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiTriggersIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiTriggersIdRequest$ {
  /** @deprecated use `DeleteApiTriggersIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteApiTriggersIdRequest$inboundSchema;
  /** @deprecated use `DeleteApiTriggersIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteApiTriggersIdRequest$outboundSchema;
  /** @deprecated use `DeleteApiTriggersIdRequest$Outbound` instead. */
  export type Outbound = DeleteApiTriggersIdRequest$Outbound;
}

export function deleteApiTriggersIdRequestToJSON(
  deleteApiTriggersIdRequest: DeleteApiTriggersIdRequest,
): string {
  return JSON.stringify(
    DeleteApiTriggersIdRequest$outboundSchema.parse(deleteApiTriggersIdRequest),
  );
}

export function deleteApiTriggersIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiTriggersIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApiTriggersIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiTriggersIdRequest' from JSON`,
  );
}

/** @internal */
export const DeleteApiTriggersIdResponseBody$inboundSchema: z.ZodType<
  DeleteApiTriggersIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
});

/** @internal */
export type DeleteApiTriggersIdResponseBody$Outbound = {
  message?: string | undefined;
};

/** @internal */
export const DeleteApiTriggersIdResponseBody$outboundSchema: z.ZodType<
  DeleteApiTriggersIdResponseBody$Outbound,
  z.ZodTypeDef,
  DeleteApiTriggersIdResponseBody
> = z.object({
  message: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiTriggersIdResponseBody$ {
  /** @deprecated use `DeleteApiTriggersIdResponseBody$inboundSchema` instead. */
  export const inboundSchema = DeleteApiTriggersIdResponseBody$inboundSchema;
  /** @deprecated use `DeleteApiTriggersIdResponseBody$outboundSchema` instead. */
  export const outboundSchema = DeleteApiTriggersIdResponseBody$outboundSchema;
  /** @deprecated use `DeleteApiTriggersIdResponseBody$Outbound` instead. */
  export type Outbound = DeleteApiTriggersIdResponseBody$Outbound;
}

export function deleteApiTriggersIdResponseBodyToJSON(
  deleteApiTriggersIdResponseBody: DeleteApiTriggersIdResponseBody,
): string {
  return JSON.stringify(
    DeleteApiTriggersIdResponseBody$outboundSchema.parse(
      deleteApiTriggersIdResponseBody,
    ),
  );
}

export function deleteApiTriggersIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiTriggersIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApiTriggersIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiTriggersIdResponseBody' from JSON`,
  );
}
