/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiUsersIdRequest = {
  /**
   * The ID of the User
   */
  id: string;
};

/** @internal */
export const GetApiUsersIdRequest$inboundSchema: z.ZodType<
  GetApiUsersIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetApiUsersIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetApiUsersIdRequest$outboundSchema: z.ZodType<
  GetApiUsersIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiUsersIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiUsersIdRequest$ {
  /** @deprecated use `GetApiUsersIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiUsersIdRequest$inboundSchema;
  /** @deprecated use `GetApiUsersIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiUsersIdRequest$outboundSchema;
  /** @deprecated use `GetApiUsersIdRequest$Outbound` instead. */
  export type Outbound = GetApiUsersIdRequest$Outbound;
}

export function getApiUsersIdRequestToJSON(
  getApiUsersIdRequest: GetApiUsersIdRequest,
): string {
  return JSON.stringify(
    GetApiUsersIdRequest$outboundSchema.parse(getApiUsersIdRequest),
  );
}

export function getApiUsersIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiUsersIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiUsersIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiUsersIdRequest' from JSON`,
  );
}
