/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiDatabasesIdRequest = {
  /**
   * The ID of the Database
   */
  id: string;
};

/** @internal */
export const GetApiDatabasesIdRequest$inboundSchema: z.ZodType<
  GetApiDatabasesIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetApiDatabasesIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetApiDatabasesIdRequest$outboundSchema: z.ZodType<
  GetApiDatabasesIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiDatabasesIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiDatabasesIdRequest$ {
  /** @deprecated use `GetApiDatabasesIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiDatabasesIdRequest$inboundSchema;
  /** @deprecated use `GetApiDatabasesIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiDatabasesIdRequest$outboundSchema;
  /** @deprecated use `GetApiDatabasesIdRequest$Outbound` instead. */
  export type Outbound = GetApiDatabasesIdRequest$Outbound;
}

export function getApiDatabasesIdRequestToJSON(
  getApiDatabasesIdRequest: GetApiDatabasesIdRequest,
): string {
  return JSON.stringify(
    GetApiDatabasesIdRequest$outboundSchema.parse(getApiDatabasesIdRequest),
  );
}

export function getApiDatabasesIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiDatabasesIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiDatabasesIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiDatabasesIdRequest' from JSON`,
  );
}
