/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiDeploymentsIdRequest = {
  /**
   * The ID of the Deployment
   */
  id: string;
};

/** @internal */
export const GetApiDeploymentsIdRequest$inboundSchema: z.ZodType<
  GetApiDeploymentsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetApiDeploymentsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetApiDeploymentsIdRequest$outboundSchema: z.ZodType<
  GetApiDeploymentsIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiDeploymentsIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiDeploymentsIdRequest$ {
  /** @deprecated use `GetApiDeploymentsIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiDeploymentsIdRequest$inboundSchema;
  /** @deprecated use `GetApiDeploymentsIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiDeploymentsIdRequest$outboundSchema;
  /** @deprecated use `GetApiDeploymentsIdRequest$Outbound` instead. */
  export type Outbound = GetApiDeploymentsIdRequest$Outbound;
}

export function getApiDeploymentsIdRequestToJSON(
  getApiDeploymentsIdRequest: GetApiDeploymentsIdRequest,
): string {
  return JSON.stringify(
    GetApiDeploymentsIdRequest$outboundSchema.parse(getApiDeploymentsIdRequest),
  );
}

export function getApiDeploymentsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiDeploymentsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiDeploymentsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiDeploymentsIdRequest' from JSON`,
  );
}
