/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiQueuesIdRequest = {
  /**
   * The ID of the Queue
   */
  id: string;
};

/** @internal */
export const GetApiQueuesIdRequest$inboundSchema: z.ZodType<
  GetApiQueuesIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetApiQueuesIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetApiQueuesIdRequest$outboundSchema: z.ZodType<
  GetApiQueuesIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiQueuesIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiQueuesIdRequest$ {
  /** @deprecated use `GetApiQueuesIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiQueuesIdRequest$inboundSchema;
  /** @deprecated use `GetApiQueuesIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiQueuesIdRequest$outboundSchema;
  /** @deprecated use `GetApiQueuesIdRequest$Outbound` instead. */
  export type Outbound = GetApiQueuesIdRequest$Outbound;
}

export function getApiQueuesIdRequestToJSON(
  getApiQueuesIdRequest: GetApiQueuesIdRequest,
): string {
  return JSON.stringify(
    GetApiQueuesIdRequest$outboundSchema.parse(getApiQueuesIdRequest),
  );
}

export function getApiQueuesIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiQueuesIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiQueuesIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiQueuesIdRequest' from JSON`,
  );
}
