/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiEvalResultsIdRequest = {
  /**
   * The ID of the Eval Result
   */
  id: string;
};

/** @internal */
export const GetApiEvalResultsIdRequest$inboundSchema: z.ZodType<
  GetApiEvalResultsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetApiEvalResultsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetApiEvalResultsIdRequest$outboundSchema: z.ZodType<
  GetApiEvalResultsIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiEvalResultsIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiEvalResultsIdRequest$ {
  /** @deprecated use `GetApiEvalResultsIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiEvalResultsIdRequest$inboundSchema;
  /** @deprecated use `GetApiEvalResultsIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiEvalResultsIdRequest$outboundSchema;
  /** @deprecated use `GetApiEvalResultsIdRequest$Outbound` instead. */
  export type Outbound = GetApiEvalResultsIdRequest$Outbound;
}

export function getApiEvalResultsIdRequestToJSON(
  getApiEvalResultsIdRequest: GetApiEvalResultsIdRequest,
): string {
  return JSON.stringify(
    GetApiEvalResultsIdRequest$outboundSchema.parse(getApiEvalResultsIdRequest),
  );
}

export function getApiEvalResultsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiEvalResultsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiEvalResultsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiEvalResultsIdRequest' from JSON`,
  );
}
