/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiIntegrationsIdRequest = {
  /**
   * The ID of the Integration
   */
  id: string;
};

/** @internal */
export const GetApiIntegrationsIdRequest$inboundSchema: z.ZodType<
  GetApiIntegrationsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetApiIntegrationsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetApiIntegrationsIdRequest$outboundSchema: z.ZodType<
  GetApiIntegrationsIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiIntegrationsIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiIntegrationsIdRequest$ {
  /** @deprecated use `GetApiIntegrationsIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiIntegrationsIdRequest$inboundSchema;
  /** @deprecated use `GetApiIntegrationsIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiIntegrationsIdRequest$outboundSchema;
  /** @deprecated use `GetApiIntegrationsIdRequest$Outbound` instead. */
  export type Outbound = GetApiIntegrationsIdRequest$Outbound;
}

export function getApiIntegrationsIdRequestToJSON(
  getApiIntegrationsIdRequest: GetApiIntegrationsIdRequest,
): string {
  return JSON.stringify(
    GetApiIntegrationsIdRequest$outboundSchema.parse(
      getApiIntegrationsIdRequest,
    ),
  );
}

export function getApiIntegrationsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiIntegrationsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiIntegrationsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiIntegrationsIdRequest' from JSON`,
  );
}
