/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiPromptsIdRequest = {
  /**
   * The ID of the Prompt
   */
  id: string;
};

/** @internal */
export const GetApiPromptsIdRequest$inboundSchema: z.ZodType<
  GetApiPromptsIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetApiPromptsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetApiPromptsIdRequest$outboundSchema: z.ZodType<
  GetApiPromptsIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiPromptsIdRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiPromptsIdRequest$ {
  /** @deprecated use `GetApiPromptsIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiPromptsIdRequest$inboundSchema;
  /** @deprecated use `GetApiPromptsIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiPromptsIdRequest$outboundSchema;
  /** @deprecated use `GetApiPromptsIdRequest$Outbound` instead. */
  export type Outbound = GetApiPromptsIdRequest$Outbound;
}

export function getApiPromptsIdRequestToJSON(
  getApiPromptsIdRequest: GetApiPromptsIdRequest,
): string {
  return JSON.stringify(
    GetApiPromptsIdRequest$outboundSchema.parse(getApiPromptsIdRequest),
  );
}

export function getApiPromptsIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiPromptsIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiPromptsIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiPromptsIdRequest' from JSON`,
  );
}
