name: Cloudflare Build and Deploy

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    name: Build and Deploy to Cloudflare
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./templates/cloudflare
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Deploy with Wrangler
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
