name: Release Next

on:
  push:
    branches:
      - next
    paths:
      - '.github/version-stamp-next.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-test:
    uses: ./.github/workflows/reusable-build-test.yml
    secrets:
      PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

  release:
    name: Release Next
    needs: build-and-test
    uses: ./.github/workflows/reusable-release.yml
    with:
      ref: 'next'
      script-path: 'scripts/release-next.js'
      force-patch: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
