name: Release SDKs

on:
  push:
    branches:
      - main
      - next
    paths:
      - '.github/version-stamp-sdks.txt'
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry Run'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      custom-command:
        description: 'Custom Command'
        required: false
        default: ''
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-test:
    uses: ./.github/workflows/reusable-build-test.yml
    secrets:
      PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

  release:
    name: Release SDKs
    needs: build-and-test
    uses: ./.github/workflows/reusable-release.yml
    with:
      ref: ${{ github.ref_name }}
      script-path: ${{ github.ref == 'refs/heads/next' && 'scripts/release-sdks-next.js' || 'scripts/release-sdks.js' }} ${{ inputs.dry-run == 'true' && '--dry-run' || '' }}
      force-patch: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
