name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

        with:
          fetch-depth: 0

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.x

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-test-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-test-

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Typecheck
        run: |
          pnpm --filter apis.do build
          pnpm --filter @drivly/ui build
          pnpm --filter @drivly/payload-agent build
          # Temporarily disabled typecheck as requested
          # pnpm typecheck
          echo "Typecheck temporarily disabled as requested"

      - name: Run Tests
        run: pnpm test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        
      - name: Start Server and Run Chromatic Tests
        run: |
          # Install required utilities
          npm install -g wait-on cross-env velite
          # Start the server in the background
          pnpm dev:content & cross-env NODE_OPTIONS=--no-deprecation npx next dev &
          # Wait for the server to be ready
          wait-on http://localhost:3000 -t 120000
          # Run Chromatic tests
          pnpm test:chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          TEST_BASE_URL: http://localhost:3000
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
