name: Update LLM Documentation and Benchmarks

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.x

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Unified LLM Fetcher
        run: node scripts/unified-llm-fetcher.js
        env:
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
          
      - name: Fetch Benchmark Data
        run: pnpm --filter ai-benchmarks generate:benchmarks
        
      - name: Check for Benchmark Changes
        id: check_benchmark_changes
        run: |
          if [[ -n "$(git status --porcelain pkgs/ai-benchmarks/src/benchmarks/)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          # Use a PAT with workflow permissions instead of GITHUB_TOKEN to trigger workflows
          # Required permissions for DOCS_WORKFLOW_PAT:
          # - Contents: read and write (for repo access)
          # - Pull Requests: read and write (for PR creation)
          # - Workflows: read and write (to trigger workflows)
          token: ${{ secrets.DOCS_WORKFLOW_PAT }}
          commit-message: "chore: update LLM documentation and benchmarks"
          branch: "auto-update/llm-docs-and-benchmarks"
          delete-branch: true
          title: "chore: update LLM documentation and benchmarks"
          body: |
            This PR was created automatically by the update-llm-docs-and-benchmarks workflow.
            It contains updated LLM documentation and benchmark data from various sources.
            
            Related to ticket: AI-13, ENG-514
          labels: |
            documentation
            automated pr
            benchmarks
