name: Vercel E2E Tests

on:
  deployment_status:
    branches:
      - main

jobs:
  e2e-tests:
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '10'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Debug Deployment Status Event
        run: |
          echo "Deployment Status Event:"
          echo "Target URL: ${{ github.event.deployment_status.target_url }}"
          echo "Environment: ${{ github.event.deployment_status.environment }}"
          echo "State: ${{ github.event.deployment_status.state }}"
          echo "GitHub Ref: ${GITHUB_REF}"
          echo "GitHub Ref Name: ${GITHUB_REF_NAME}"
          echo "GitHub Head Ref: ${GITHUB_HEAD_REF}"

      - name: Set Vercel Preview URL
        run: |
          # Primary approach: Use the target URL from the deployment_status event
          DEPLOY_URL="${{ github.event.deployment_status.target_url }}"
          
          # Fallback 1: If target_url is empty, try to extract from other fields
          if [ -z "$DEPLOY_URL" ]; then
            echo "Target URL is empty, trying to extract from description..."
            DEPLOY_URL=$(echo "${{ github.event.deployment_status.description }}" | grep -o 'https://[^ ]*' || echo "")
          fi
          
          # Fallback 2: Construct URL from branch name if still empty
          if [ -z "$DEPLOY_URL" ]; then
            echo "Still no URL, using branch name-based URL construction..."
            BRANCH_NAME=$(echo ${GITHUB_REF_NAME:-${GITHUB_REF#refs/heads/}} | sed 's/\//-/g')
            DEPLOY_URL="https://ai-git-${BRANCH_NAME}.dev.driv.ly"
          fi
          
          echo "VERCEL_PREVIEW_URL=${DEPLOY_URL}" >> $GITHUB_ENV
          echo "Using Vercel Preview URL: ${DEPLOY_URL}"

      - name: Run E2E tests on Vercel Preview
        env:
          BASE_URL: ${{ env.VERCEL_PREVIEW_URL }}
          BROWSER_TESTS: 'true'
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
        run: |
          cp tests/vitest.e2e.config.ts ./vitest.e2e.config.ts
          echo "Testing against BASE_URL: ${BASE_URL}"
          pnpm test:e2e
