name: Vercel E2E Tests

on:
  deployment_status:
    branches:
      - main

jobs:
  e2e-tests:
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '10'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
        
      - name: Set Vercel Preview URL
        run: |
          echo "VERCEL_PREVIEW_URL=https://ai-git-${BRANCH_NAME}.dev.driv.ly" >> $GITHUB_ENV
          echo "Using Vercel Preview URL: https://ai-git-${BRANCH_NAME}.dev.driv.ly"

      - name: Run E2E tests on Vercel Preview
        env:
          BASE_URL: ${{ env.VERCEL_PREVIEW_URL }}
          BROWSER_TESTS: 'true'
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
        run: |
          cp tests/vitest.e2e.config.ts ./vitest.e2e.config.ts
          echo "Testing against BASE_URL: ${BASE_URL}"
          pnpm test:e2e
