name: Version PR

on:
  push:
    branches:
      - version-*

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pr:
    name: Create Version PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.x

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Create Release PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: version packages"
          branch: version-pr
          delete-branch: true
          title: "chore: version packages"
          body: |
            This PR was created by the multi-semantic-release action.
            It contains version updates for all packages that have changes.
          labels: |
            version
            automated pr
